name: CI

on:
  push:
    branches: [main]
  
  workflow_dispatch:

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: shell.ter
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache-dependency-path: shell.ter/package-lock.json
      - name: Install dependencies
        run: npm i
      - name: Run tests
        run: npm test
      - name: Run e2e tests
        run: npm run test:e2e
  backend-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: shell.ter
    needs: backend
    concurrency: heroku-deploy
    steps:
      - uses: actions/checkout@v2
      - name: Build and deploy on Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          appdir: shell.ter
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: shell-ter
          heroku_email: pettko.harsanyi@gmail.com
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: shell.ter-client
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache-dependency-path: shell.ter-client/package-lock.json
      - name: Install dependencies
        run: npm i
      - name: Run tests
        run: npm test
  frontend-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: shell.ter-client
    needs: frontend
    concurrency: heroku-deploy
    steps:
      - uses: actions/checkout@v2
      - name: Build and deploy on Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          appdir: shell.ter-client
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: shell-ter-client
          heroku_email: pettko.harsanyi@gmail.com